analytics: {}
color:
  brandColors:
    - '#D0D0D0'
    - '#700000'
    - '#808088'
    - '#D00000'
    - '#000000'
  brandStrength: 1
  lightness: 0.710304
  rhythmicContrast: 0.358108
  saturation: 0.255912
cta: {}
layout_spectrum: 0.733952
name: Triradiate
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.80152
