name: triradiate
favicon: null
layout_spectrum: 0.740709
typography_spectrum: 0.924831
title: Triradiate Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0D0D0'
    - '#700000'
    - '#808088'
    - '#D00000'
    - '#000000'
  brandStrength: 0.793918
  lightness: 0.794763
  saturation: 0.643581
  rhythmicContrast: 0.706925
purpose:
  - name: null
    item: null
    url: null
