analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#9F9F9F'
    - '#DB0505'
    - '#070000'
    - '#333437'
  brandStrength: 0.5
  lightness: 0.9375
  rhythmicContrast: 0
  saturation: 0.255912
cta: {}
layout_spectrum: 0.239864
name: Triradiate
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.80152
